### PR TITLE
SampleLost test: induce a sample lost event

### LINKED ISSUE #2095: SampleLost test doesn't get any sample lost
The tests/DCPS/SampleLost doesn't see any samples lost happening, this looks incorrect, in some of my testing I would also expect to get a sample_lost but didn't got it, so tried this unit test, which also seems to not get a sample lost

### PR DESCRIPTION
**Pull request by mitza-oci**
Replaces #2096
May fix #2095

### CODE REVIEW

**Review by jwillemsen — APPROVED** [review]

File: tests/DCPS/SampleLost/DataReaderListener.cpp [hunk 1]
```diff
@@ -24,37 +24,7 @@ DataReaderListenerImpl::~DataReaderListenerImpl ()
 void
 DataReaderListenerImpl::on_data_available(DDS::DataReader_ptr reader)
```
Comment (simpsont-oci) [inline tests/DCPS/SampleLost/DataReaderListener.cpp:25]:
```suggestion
DataReaderListenerImpl::on_data_available(DDS::DataReader_ptr /*reader/*)
```
